//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 10:23:06 AM ART 
//


package qc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Field" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="History" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="List-Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="System" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Verify" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Virtual" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Visible" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Editable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Filterable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Groupable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SupportsMultivalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="PhysicalName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "field"
})
@XmlRootElement(name = "Fields")
public class Fields {

    @XmlElement(name = "Field")
    protected List<Fields.Field> field;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fields.Field }
     * 
     * 
     */
    public List<Fields.Field> getField() {
        if (field == null) {
            field = new ArrayList<Fields.Field>();
        }
        return this.field;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="History" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="List-Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="System" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Verify" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Virtual" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Visible" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Editable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Filterable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Groupable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SupportsMultivalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="PhysicalName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "size",
        "history",
        "listId",
        "required",
        "system",
        "type",
        "verify",
        "virtual",
        "active",
        "visible",
        "editable",
        "filterable",
        "groupable",
        "supportsMultivalue"
    })
    public static class Field {

        @XmlElement(name = "Size")
        protected short size;
        @XmlElement(name = "History", required = true)
        protected String history;
        @XmlElement(name = "List-Id")
        protected Integer listId;
        @XmlElement(name = "Required", required = true)
        protected String required;
        @XmlElement(name = "System", required = true)
        protected String system;
        @XmlElement(name = "Type", required = true)
        protected String type;
        @XmlElement(name = "Verify", required = true)
        protected String verify;
        @XmlElement(name = "Virtual", required = true)
        protected String virtual;
        @XmlElement(name = "Active", required = true)
        protected String active;
        @XmlElement(name = "Visible", required = true)
        protected String visible;
        @XmlElement(name = "Editable", required = true)
        protected String editable;
        @XmlElement(name = "Filterable", required = true)
        protected String filterable;
        @XmlElement(name = "Groupable", required = true)
        protected String groupable;
        @XmlElement(name = "SupportsMultivalue", required = true)
        protected String supportsMultivalue;
        @XmlAttribute(name = "PhysicalName")
        protected String physicalName;
        @XmlAttribute(name = "Name")
        protected String name;
        @XmlAttribute(name = "Label")
        protected String label;

        /**
         * Gets the value of the size property.
         * 
         */
        public short getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         */
        public void setSize(short value) {
            this.size = value;
        }

        /**
         * Gets the value of the history property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHistory() {
            return history;
        }

        /**
         * Sets the value of the history property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHistory(String value) {
            this.history = value;
        }

        /**
         * Gets the value of the listId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getListId() {
            return listId;
        }

        /**
         * Sets the value of the listId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setListId(Integer value) {
            this.listId = value;
        }

        /**
         * Gets the value of the required property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequired() {
            return required;
        }

        /**
         * Sets the value of the required property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequired(String value) {
            this.required = value;
        }

        /**
         * Gets the value of the system property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystem() {
            return system;
        }

        /**
         * Sets the value of the system property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystem(String value) {
            this.system = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the verify property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerify() {
            return verify;
        }

        /**
         * Sets the value of the verify property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerify(String value) {
            this.verify = value;
        }

        /**
         * Gets the value of the virtual property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVirtual() {
            return virtual;
        }

        /**
         * Sets the value of the virtual property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVirtual(String value) {
            this.virtual = value;
        }

        /**
         * Gets the value of the active property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActive(String value) {
            this.active = value;
        }

        /**
         * Gets the value of the visible property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisible() {
            return visible;
        }

        /**
         * Sets the value of the visible property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisible(String value) {
            this.visible = value;
        }

        /**
         * Gets the value of the editable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEditable() {
            return editable;
        }

        /**
         * Sets the value of the editable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEditable(String value) {
            this.editable = value;
        }

        /**
         * Gets the value of the filterable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilterable() {
            return filterable;
        }

        /**
         * Sets the value of the filterable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilterable(String value) {
            this.filterable = value;
        }

        /**
         * Gets the value of the groupable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroupable() {
            return groupable;
        }

        /**
         * Sets the value of the groupable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroupable(String value) {
            this.groupable = value;
        }

        /**
         * Gets the value of the supportsMultivalue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupportsMultivalue() {
            return supportsMultivalue;
        }

        /**
         * Sets the value of the supportsMultivalue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupportsMultivalue(String value) {
            this.supportsMultivalue = value;
        }

        /**
         * Gets the value of the physicalName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhysicalName() {
            return physicalName;
        }

        /**
         * Sets the value of the physicalName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhysicalName(String value) {
            this.physicalName = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

    }

}